src/accounting_system/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", include("apps.login.urls")),
    path("requests/", include("apps.requests.urls")),
    path("teams/", include("apps.teams.urls")),
    path("registration/", include("apps.registration.urls")),
    path("emailContact/", include("apps.emailContact.urls")),
    path("permissions/", include("apps.permissions.urls")),
    path("error/", include("apps.errorHandler.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = "apps.errorHandler.views.error_404_view"

src/apps/login/urls.py
"""
Request urls

This module defines URL patterns for the login application.
"""

from django.urls import path
from . import views

app_name = "login"

urlpatterns = [
    path("", views.login_view, name="login_view"),
    path("logout/", views.login_view, name="login_view"),
    path("resetPassword/", views.reset_password_view, name="reset_password_view"),
    path(
        "resetPassword/verifyIdentity/",
        views.verify_email_reset_view,
        name="verify_email_reset_view",
    ),
    path("changePassword/", views.change_password_view, name="change_password_view"),
    path("verifyEmail/", views.verify_email_view, name="verifyEmail_view"),
]

src/apps/registration/urls.py
"""
Registration urls

This module defines URL patterns for the registration application.
"""

from django.urls import path
from . import views

app_name = "registration"

urlpatterns = [
    path("", views.register_view, name="register_view"),
    path("verifyEmail/", views.verify_email_view, name="verifyEmail_view"),
]

src/apps/login/models.py
from django.db import models

# Create your models here.

src/apps/login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import get_user_model
from apps.requests import views
from django.contrib import messages
import utils.utils as utils


User = get_user_model()


# Global variable to store the random code
global random_code


# Create your views here.
def login_view(request):
    """Handles user login and session management.

    GET: Renders the login page.
    POST: Authenticates user credentials, generates and sends a verification email for account confirmation.

    Args:
        request: HttpRequest object.

    Returns:
        GET: Rendered login page.
        POST: Redirects to 'login:verifyEmail_view' if authentication is successful; else, renders the login page with an error message.
    """
    if request.method == "GET":
        request.session["has_logged"] = False
        request.session["has_requested_password"] = False
        if request.user.is_authenticated and request.GET.get("logout") != "true":
            return redirect("/requests")
        else:
            if request.GET.get("logout") == "true":
                logout(request)
            return render(request, "login.html")
    else:
        try:
            user = authenticate(
                request,
                id=request.POST["usuario"],
                password=request.POST["contrasena"],
            )

            if user is not None:
                request.session["user_id"] = user.id

                # Generate random code
                random_code = utils.generate_random_code()
                request.session["random_code"] = random_code
                # print("Code: " + random_code)

                # Send verification email
                utils.send_verification_email(
                    request,
                    "Verificación de correo",
                    "Verificación de Registro Vía Sistema de Contabilidad | Universidad Icesi <contabilidad@icesi.edu.co>",
                    user.email,
                    "Hola, bienvenido al Sistema de Contabilidad de la Universidad ICESI.\n\nSu código de verificación es: "
                    + random_code
                    + "\n\nSi no ha solicitado este correo, por favor ignorelo.",
                )
                request.session["has_logged"] = True

                return redirect("login:verifyEmail_view")
            else:
                return render(
                    request,
                    "login.html",
                    {"message": "Por favor, revisa las credenciales."},
                )
        except Exception as e:
            print(e)
            return render(
                request,
                "login.html",
                {"message": "Ingrese un usuario válido."},
            )


# Verification after login
def verify_email_view(request):
    """Handles verification after login using a verification code.

    GET: Renders the verification page.
    POST: Verifies the entered verification code and logs the user in if successful; else, displays an error message.

    Args:
        request: HttpRequest object.

    Returns:
        GET: Rendered verification page.
        POST: Redirects to '/requests/' if verification is successful; else, renders the verification page with an error message.
    """
    context = {"form_action": "login:verifyEmail_view"}
    if request.method == "GET":
        if request.session.get("has_logged") == True:
            return render(request, "verifyEmailLog.html", context)
        else:
            if request.user.is_authenticated:
                return redirect("/requests/")
            else:
                return redirect("login:login_view")
    else:
        if request.POST["verificationCode"] == request.session.get("random_code"):
            user_id = request.session.get("user_id")
            user = User.objects.get(id=user_id)
            backend = "django.contrib.auth.backends.ModelBackend"
            user.backend = backend
            login(request, user)
            return redirect("/requests/")
        else:
            messages.error(request, "Código de verificación incorrecto.")
            return render(request, "verifyEmailLog.html", context)


"""
Change password methods

1. reset_password_view: Request id after clicking "Forgot password?"
2. verify_email_reset_view: Verification after putting id in "Forgot password?" to verify identity
3. change_password_view: Change password after verifying identity
4. Return to login_view after changing password
"""


# Request id after clicking "Forgot password?"
def reset_password_view(request):
    """Handles the request to reset the password.

    GET: Renders the reset password page.
    POST: Sends a verification email for password reset if the user exists; else, displays an error message.

    Args:
        request: HttpRequest object.

    Returns:
        GET: Rendered reset password page.
        POST: Redirects to 'login:verify_email_reset_view' if user exists; else, renders the reset password page with an error message.
    """
    if request.method == "GET":
        return render(request, "reset_password.html")
    else:
        id = request.POST["userId"]
        if User.objects.filter(id=id).exists():
            request.session["user_id"] = id
            # Generate random code
            random_code = utils.generate_random_code()
            request.session["random_code"] = random_code
            # print("Code: " + random_code)
            user = User.objects.get(id=id)
            email = user.email
            # Send verification email
            utils.send_verification_email(
                request,
                "Verificación de correo",
                "Verificación de Registro Vía Sistema de Contabilidad | Universidad Icesi <contabilidad@icesi.edu.co>",
                email,
                "Hola, se ha solicitado un cambio de contraseña.\n\nSu código de verificación es: "
                + random_code
                + "\n\nSi no ha solicitado este cambio, ignore este mensaje.",
            )
            request.session["has_requested_password"] = True
            return redirect("login:verify_email_reset_view")
        else:
            messages.error(request, "Usuario no encontrado.")
            return render(request, "reset_password.html")


# Verification after putting id in "Forgot password?" to verify identity
def verify_email_reset_view(request):
    """Handles verification after requesting a password reset.

    GET: Renders the verification page.
    POST: Verifies the entered verification code and redirects to 'login:change_password_view' if successful; else, displays an error message.

    Args:
        request: HttpRequest object.

    Returns:
        GET: Rendered verification page.
        POST: Redirects to 'login:change_password_view' if verification is successful; else, renders the verification page with an error message.
    """
    context = {"form_action": "login:verify_email_reset_view"}
    if request.method == "GET":
        if request.session.get("has_requested_password") == True:
            return render(request, "verifyEmailLog.html", context)
        else:
            if request.user.is_authenticated:
                return redirect("/requests")
            else:
                return redirect("login:login_view")
    else:
        if request.POST["verificationCode"] == request.session.get("random_code"):
            return redirect("login:change_password_view")
        else:
            messages.error(request, "Código de verificación incorrecto.")
            return render(request, "verifyEmailLog.html", context)


# Change password after verifying identity
def change_password_view(request):
    """Handles password change after verifying identity.

    GET: Renders the change password page.
    POST: Changes the password if password criteria are met; else, displays an error message.

    Args:
        request: HttpRequest object.

    Returns:
        GET: Rendered change password page.
        POST: Redirects to 'login:login_view' if password is changed successfully; else, renders the change password page with an error message.
    """
    if request.method == "GET":
        if request.session.get("has_requested_password") == True:
            return render(request, "change_password.html")
        else:
            if request.user.is_authenticated:
                return redirect("/requests")
            else:
                return redirect("login:login_view")
    else:
        password = request.POST["password"]
        confirm_password = request.POST["confirmPassword"]
        if password == confirm_password:
            if len(password) < 8:
                messages.error(
                    request, "La contraseña debe tener al menos 8 caracteres."
                )
                return render(request, "change_password.html")
            else:
                user = User.objects.get(id=request.session.get("user_id"))
                user.set_password(password)
                user.save()
                messages.success(
                    request, "Las contraseña fue actualizada correctamente."
                )
                return redirect("login:login_view")
        else:
            messages.error(request, "Las contraseñas no coinciden.")
            return render(request, "change_password.html")

src/apps/login/templates/change_password.html
<!DOCTYPE html>
{% load static %}
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--Bootstrap-->
    <title>Reset Password</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!--Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.1/css/all.css" crossorigin="anonymous">
    <!--CSS-->
    <link rel="stylesheet" href="{% static 'registration/css/register.css' %}" />

    <style>

        .card {
            border-radius: 35px !important;
            box-shadow: 0 0 8px rgba(0, 0, 0, 0.1);
            background-color: #589BFF;
            width: 100%;
            width: auto;
            height: auto;
            margin: 0 auto;
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 30px;
        }

    </style>
</head>


<body style="background-color: #F6F7F8">
    <div class="container mt-5">
        <div class="mb-5">
            <img src="{% static 'login/assets/logo.png' %}" alt="Logo" class="img-fluid" style="max-width: 350px;">
        </div>
        <div class="row justify-content-center">
            <div class="col-md-6">

                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                {% endif %}
                
                <div class="card">
                    <h3 class="titulo-inicio text-center fw-bold fs-2 text-white "> Cambio de contraseña </h3>
                    <div class="card-body">
                        <form action="{% url 'login:change_password_view' %}" method="POST">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="userId" class="form-label text-white">Por favor, ingrese su nueva contraseña.</label>
                                <div class="input-container mb-3 mt-4">
                                    <input type="password" class="form-control" placeholder="Ingrese su contraseña" id="password" name="password" required>
                                    <i class="fa fa-user icon"></i>
                                </div>
                                <div class="input-container mb-3 mt-4">
                                    <input type="password" class="form-control" placeholder="Repita su contraseña" id="confirmPassword" name="confirmPassword" required>
                                    <i class="fa fa-user icon"></i>
                                </div>
                            </div>
                            <div class="d-flex justify-content-center">
                                <button type="submit" class="btn btn-primary mt-4">Continuar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

src/apps/login/templates/email_template.html
{{message}}

src/apps/login/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--Bootstrap-->
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!--Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.1/css/all.css" crossorigin="anonymous">
    <!--CSS-->
    <link rel="stylesheet" href="{% static 'login/css/login.css' %}" />

    <style>
        body {
            background-color: #F6F7F8;
        }

        .card {
            border-radius: 35px !important;
            box-shadow: 0 0 8px rgba(0, 0, 0, 0.1);
            background-color: #589BFF;
            width: 100%;
            width: 450px;
            height: 450px;
            margin: 0 auto;
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 30px;
        }

        .card-header {
            font-weight: 900;
            border-radius: 35px !important;
            background-color: #589BFF;
            color: #fff;
            border-bottom: none;
        }

        .card-body {
            width: 100%;
            padding: 20px;
        }

        .card-body input,
        .card-body label {
            margin-bottom: 15px;
        }
    </style>
</head>


<body>

    <div class="container mt-5">
        <div class="mb-5">
            <img src="{% static 'login/assets/logo.png' %}" alt="Logo" class="img-fluid" style="max-width: 350px;">
        </div>
        <div class="row justify-content-center">
            <div class="col-md-6">

                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                {% elif message %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        {{message}}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endif %}

                <div class="card">
                    <div class="card-header">
                        <h3 class="titulo-inicio text-center"> Inicio de Sesión</h3>
                    </div>
                    <div class="card-body">
                        <form action="/" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="input-container">
                                    <input type="text" class="form-control" id="usuario" name="usuario"
                                        placeholder="Ingresa tu usuario" required>
                                    <i class="fa fa-user icon"></i>
                                </div>
                                <div class="input-container">
                                    <input type="password" class="form-control" id="contrasena" name="contrasena"
                                        placeholder="Ingresa tu contraseña" required>
                                    <i class="fa fa-lock icon"></i>
                                </div>
                            </div>
                            <div class="card-body text-center">
                                <form>
                                    <button type="submit" class="btn btn-primary mt-2">INICIAR SESIÓN</button>
                                </form>
                            </div>
                        </form>
                    </div>
                    <div class="d-flex flex-column align-items-center">
                        <a href="{% url 'registration:register_view' %}" class="btn btn-link text-primary text-decoration-underline">Registrarse</a>
                        <a href="{% url 'login:reset_password_view' %}" class="btn btn-link text-primary text-decoration-underline">¿Olvidaste tu contraseña?</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

src/apps/login/templates/reset_password.html
<!DOCTYPE html>
{% load static %}
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--Bootstrap-->
    <title>Reset Password</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!--Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.1/css/all.css" crossorigin="anonymous">
    <!--CSS-->
    <link rel="stylesheet" href="{% static 'registration/css/register.css' %}" />

    <style>

        .card {
            border-radius: 35px !important;
            box-shadow: 0 0 8px rgba(0, 0, 0, 0.1);
            background-color: #589BFF;
            width: 100%;
            width: auto;
            height: auto;
            margin: 0 auto;
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 30px;
        }

    </style>
</head>


<body style="background-color: #F6F7F8">
    <div class="container mt-5">
        <div class="mb-5">
            <img src="{% static 'login/assets/logo.png' %}" alt="Logo" class="img-fluid" style="max-width: 350px;">
        </div>
        <div class="row justify-content-center">
            <div class="col-md-6">

                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                {% endif %}
                
                <div class="card">
                    <h3 class="titulo-inicio text-center fw-bold fs-2 text-white "> Recuperación de contraseña </h3>
                    <div class="card-body">
                        <form action="{% url 'login:reset_password_view' %}" method="POST">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="userId" class="form-label text-white">Por favor, ingrese su cédula para iniciar el proceso de restablecimiento de contraseña.</label>
                                <div class="input-container mb-3 mt-4">
                                    <input type="text" class="form-control" placeholder="Ingrese su cédula" id="userId" name="userId" required>
                                    <i class="fa fa-user icon"></i>
                                </div>
                            </div>
                            <div class="d-flex justify-content-center">
                                <button type="submit" class="btn btn-primary mt-4">Continuar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

src/apps/login/templates/verifyEmailLog.html
<!DOCTYPE html>
{% load static %}
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--Bootstrap-->
    <title>Verify email</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!--Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.1/css/all.css" crossorigin="anonymous">
    <!--CSS-->
    <link rel="stylesheet" href="{% static 'registration/css/register.css' %}" />

    <style>

        .card {
            border-radius: 35px !important;
            box-shadow: 0 0 8px rgba(0, 0, 0, 0.1);
            background-color: #589BFF;
            width: 100%;
            width: auto;
            height: auto;
            margin: 0 auto;
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 30px;
        }

    </style>
</head>


<body style="background-color: #F6F7F8">
    <div class="container mt-5">
        <div class="mb-5">
            <img src="{% static 'login/assets/logo.png' %}" alt="Logo" class="img-fluid" style="max-width: 350px;">
        </div>
        <div class="row justify-content-center">
            <div class="col-md-6">

                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                {% endif %}
                
                <div class="card">
                    <h3 class="titulo-inicio text-center fw-bold fs-2 text-white "> Verificación de email</h3>
                    <div class="card-body">
                        <form action="{% url form_action %}" method="POST">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="verificationCode" class="form-label text-white">Ingrese el código de verificación que enviamos al email asociado a su cuenta.</label>
                                <div class="input-container mb-3 mt-4">
                                    <input type="text" class="form-control" placeholder="Código de verificación" id="verificationCode" name="verificationCode" required>
                                    <i class="fa fa-key icon"></i>
                                </div>
                            </div>
                            <div class="d-flex justify-content-center">
                                <button type="submit" class="btn btn-primary mt-4">Verificar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>